// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.AspNetCore.Components.Rendering;

#pragma warning disable CA2252

namespace Blazonia.Components
{
    /// <summary>
    /// Base class for controls which decorate a single child control.
    /// </summary>
    public partial class Decorator : Control
    {
        static Decorator()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the padding to place around the <see cref="P:Avalonia.Controls.Decorator.Child" /> control.
        /// </summary>
        [Parameter] public OneOf.OneOf<global::Avalonia.Thickness?, double, (double, double), (double, double, double, double), string> Padding { get; set; }
        /// <summary>
        /// Gets or sets the decorated control.
        /// </summary>
        [Parameter] public RenderFragment ChildContent { get; set; }

        public new AC.Decorator NativeControl => (AC.Decorator)((AvaloniaObject)this).NativeControl;

        protected override AC.Decorator CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Padding):
                    if (!Equals(Padding, value))
                    {
                        Padding = (OneOf.OneOf<global::Avalonia.Thickness?, double, (double, double), (double, double, double, double), string>)value;
                        if (Padding.IsT0)
                        {
                            NativeControl.Padding = (global::Avalonia.Thickness)Padding.AsT0;
                        }
                        else if (Padding.IsT1)
                        {
                            NativeControl.Padding = new global::Avalonia.Thickness(Padding.AsT1);
                        }
                        else if (Padding.IsT2)
                        {
                            NativeControl.Padding = new global::Avalonia.Thickness(Padding.AsT2.Item1,Padding.AsT2.Item2);
                        }
                        else if (Padding.IsT3)
                        {
                            NativeControl.Padding = new global::Avalonia.Thickness(Padding.AsT3.Item1,Padding.AsT3.Item2,Padding.AsT3.Item3,Padding.AsT3.Item4);
                        }
                        else 
                        {
                            NativeControl.Padding = global::Avalonia.Thickness.Parse(Padding.AsT4);
                        }
                    }
                    break;
                case nameof(ChildContent):
                    ChildContent = (RenderFragment)value;
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddContentProperty<AC.Decorator>(builder, sequence++, ChildContent,
                (nativeControl, data) => nativeControl.Child = (AC.Control)data);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
