// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>



#pragma warning disable CA2252

namespace Blazonia.Components
{
    /// <summary>
    /// Defines a flexible grid area that consists of columns and rows.
    /// </summary>
    public partial class Grid : Panel
    {
        static Grid()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Returns a ColumnDefinitions of column definitions.
        /// </summary>
        [Parameter] public OneOf.OneOf<AC.ColumnDefinitions, string> ColumnDefinitions { get; set; }
        /// <summary>
        /// Returns a RowDefinitions of row definitions.
        /// </summary>
        [Parameter] public OneOf.OneOf<AC.RowDefinitions, string> RowDefinitions { get; set; }
        /// <summary>
        /// ShowGridLines property.
        /// </summary>
        [Parameter] public bool? ShowGridLines { get; set; }

        public new AC.Grid NativeControl => (AC.Grid)((AvaloniaObject)this).NativeControl;

        protected override AC.Grid CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(ColumnDefinitions):
                    if (!Equals(ColumnDefinitions, value))
                    {
                        ColumnDefinitions = (OneOf.OneOf<AC.ColumnDefinitions,string>)value;
                        if (ColumnDefinitions.IsT0)
                        {
                            NativeControl.ColumnDefinitions = (AC.ColumnDefinitions)ColumnDefinitions.AsT0;
                        }
                        else 
                        {
                            NativeControl.ColumnDefinitions = AC.ColumnDefinitions.Parse(ColumnDefinitions.AsT1);
                        }
                    }
                    break;
                case nameof(RowDefinitions):
                    if (!Equals(RowDefinitions, value))
                    {
                        RowDefinitions = (OneOf.OneOf<AC.RowDefinitions,string>)value;
                        if (RowDefinitions.IsT0)
                        {
                            NativeControl.RowDefinitions = (AC.RowDefinitions)RowDefinitions.AsT0;
                        }
                        else 
                        {
                            NativeControl.RowDefinitions = AC.RowDefinitions.Parse(RowDefinitions.AsT1);
                        }
                    }
                    break;
                case nameof(ShowGridLines):
                    if (!Equals(ShowGridLines, value))
                    {
                        ShowGridLines = (bool?)value;
                        NativeControl.ShowGridLines = ShowGridLines ?? (bool)AC.Grid.ShowGridLinesProperty.GetDefaultValue(AC.Grid.ShowGridLinesProperty.OwnerType);
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
