// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.AspNetCore.Components.Rendering;

#pragma warning disable CA2252

namespace Blazonia.Components
{
    /// <summary>
    /// Base class for controls that can contain multiple children.
    /// </summary>
    public partial class Panel : Control
    {
        static Panel()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or Sets Panel background brush.
        /// </summary>
        [Parameter] public OneOf.OneOf<global::Avalonia.Media.IBrush, global::Avalonia.Media.Color, string> Background { get; set; }
        /// <summary>
        /// Gets the children of the <see cref="T:Avalonia.Controls.Panel" />.
        /// </summary>
        [Parameter] public RenderFragment ChildContent { get; set; }

        public new AC.Panel NativeControl => (AC.Panel)((AvaloniaObject)this).NativeControl;

        protected override AC.Panel CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Background):
                    if (!Equals(Background, value))
                    {
                        Background = (OneOf.OneOf<global::Avalonia.Media.IBrush, Avalonia.Media.Color, string>)value;
                        if (Background.IsT0)
                        {
                            NativeControl.Background = (global::Avalonia.Media.IBrush)Background.AsT0;
                        }
                        else if (Background.IsT1)
                        {
                            NativeControl.Background = new global::Avalonia.Media.Immutable.ImmutableSolidColorBrush(Background.AsT1);
                        }
                        else 
                        {
                            NativeControl.Background = Avalonia.Media.Brush.Parse(Background.AsT2);
                        }
                    }
                    break;
                case nameof(ChildContent):
                    ChildContent = (RenderFragment)value;
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddListContentProperty<AC.Panel, AC.Control>(builder, sequence++, ChildContent,
                nativeControl => nativeControl.Children);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
