// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using AM = Avalonia.Media;
using Blazonia.Components;

#pragma warning disable CA2252

namespace Blazonia.Components.Media
{
    /// <summary>
    /// Fills an area with a solid color.
    /// </summary>
    public partial class SolidColorBrush : Brush
    {
        static SolidColorBrush()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the color of the brush.
        /// </summary>
        [Parameter] public OneOf.OneOf<AM.Color?, string> Color { get; set; }

        public new AM.SolidColorBrush NativeControl => (AM.SolidColorBrush)((AvaloniaObject)this).NativeControl;

        protected override AM.SolidColorBrush CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Color):
                    if (!Equals(Color, value))
                    {
                        Color = (OneOf.OneOf<AM.Color?,string>)value;
                        if (Color.IsT0)
                        {
                            NativeControl.Color = (AM.Color)Color.AsT0;
                        }
                        else 
                        {
                            NativeControl.Color = AM.Color.Parse(Color.AsT1);
                        }
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
