// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using ACP = Avalonia.Controls.Primitives;
using Blazonia.Components;
using Microsoft.AspNetCore.Components.Rendering;

#pragma warning disable CA2252

namespace Blazonia.Components.Primitives
{
    /// <summary>
    /// A lookless control whose visual appearance is defined by its <see cref="P:Avalonia.Controls.Primitives.TemplatedControl.Template" />.
    /// </summary>
    public partial class TemplatedControl : Blazonia.Components.Control
    {
        static TemplatedControl()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the brush used to draw the control's background.
        /// </summary>
        [Parameter] public OneOf.OneOf<global::Avalonia.Media.IBrush, global::Avalonia.Media.Color, string> Background { get; set; }
        /// <summary>
        /// Gets or sets how the control's background is drawn relative to the control's border.
        /// </summary>
        [Parameter] public global::Avalonia.Media.BackgroundSizing? BackgroundSizing { get; set; }
        /// <summary>
        /// Gets or sets the brush used to draw the control's border.
        /// </summary>
        [Parameter] public OneOf.OneOf<global::Avalonia.Media.IBrush, global::Avalonia.Media.Color, string> BorderBrush { get; set; }
        /// <summary>
        /// Gets or sets the thickness of the control's border.
        /// </summary>
        [Parameter] public OneOf.OneOf<global::Avalonia.Thickness?, double, (double, double), (double, double, double, double), string> BorderThickness { get; set; }
        /// <summary>
        /// Gets or sets the radius of the border rounded corners.
        /// </summary>
        [Parameter] public OneOf.OneOf<global::Avalonia.CornerRadius?, double, (double, double), (double, double, double, double), string> CornerRadius { get; set; }
        /// <summary>
        /// Gets or sets the font family used to draw the control's text.
        /// </summary>
        [Parameter] public OneOf.OneOf<global::Avalonia.Media.FontFamily, string> FontFamily { get; set; }
        /// <summary>
        /// Gets or sets the font features turned on/off.
        /// </summary>
        [Parameter] public global::Avalonia.Media.FontFeatureCollection FontFeatures { get; set; }
        /// <summary>
        /// Gets or sets the size of the control's text in points.
        /// </summary>
        [Parameter] public double? FontSize { get; set; }
        /// <summary>
        /// Gets or sets the font stretch used to draw the control's text.
        /// </summary>
        [Parameter] public global::Avalonia.Media.FontStretch? FontStretch { get; set; }
        /// <summary>
        /// Gets or sets the font style used to draw the control's text.
        /// </summary>
        [Parameter] public global::Avalonia.Media.FontStyle? FontStyle { get; set; }
        /// <summary>
        /// Gets or sets the font weight used to draw the control's text.
        /// </summary>
        [Parameter] public global::Avalonia.Media.FontWeight? FontWeight { get; set; }
        /// <summary>
        /// Gets or sets the brush used to draw the control's text and other foreground elements.
        /// </summary>
        [Parameter] public OneOf.OneOf<global::Avalonia.Media.IBrush, global::Avalonia.Media.Color, string> Foreground { get; set; }
        /// <summary>
        /// Gets or sets the padding placed between the border of the control and its content.
        /// </summary>
        [Parameter] public OneOf.OneOf<global::Avalonia.Thickness?, double, (double, double), (double, double, double, double), string> Padding { get; set; }
        /// <summary>
        /// Gets or sets the template that defines the control's appearance.
        /// </summary>
        [Parameter] public RenderFragment Template { get; set; }
        [Parameter] public EventCallback<ACP.TemplateAppliedEventArgs> OnTemplateApplied { get; set; }

        public new ACP.TemplatedControl NativeControl => (ACP.TemplatedControl)((AvaloniaObject)this).NativeControl;

        protected override ACP.TemplatedControl CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Background):
                    if (!Equals(Background, value))
                    {
                        Background = (OneOf.OneOf<global::Avalonia.Media.IBrush, Avalonia.Media.Color, string>)value;
                        if (Background.IsT0)
                        {
                            NativeControl.Background = (global::Avalonia.Media.IBrush)Background.AsT0;
                        }
                        else if (Background.IsT1)
                        {
                            NativeControl.Background = new global::Avalonia.Media.Immutable.ImmutableSolidColorBrush(Background.AsT1);
                        }
                        else 
                        {
                            NativeControl.Background = Avalonia.Media.Brush.Parse(Background.AsT2);
                        }
                    }
                    break;
                case nameof(BackgroundSizing):
                    if (!Equals(BackgroundSizing, value))
                    {
                        BackgroundSizing = (global::Avalonia.Media.BackgroundSizing?)value;
                        NativeControl.BackgroundSizing = BackgroundSizing ?? (global::Avalonia.Media.BackgroundSizing)ACP.TemplatedControl.BackgroundSizingProperty.GetDefaultValue(ACP.TemplatedControl.BackgroundSizingProperty.OwnerType);
                    }
                    break;
                case nameof(BorderBrush):
                    if (!Equals(BorderBrush, value))
                    {
                        BorderBrush = (OneOf.OneOf<global::Avalonia.Media.IBrush, Avalonia.Media.Color, string>)value;
                        if (BorderBrush.IsT0)
                        {
                            NativeControl.BorderBrush = (global::Avalonia.Media.IBrush)BorderBrush.AsT0;
                        }
                        else if (BorderBrush.IsT1)
                        {
                            NativeControl.BorderBrush = new global::Avalonia.Media.Immutable.ImmutableSolidColorBrush(BorderBrush.AsT1);
                        }
                        else 
                        {
                            NativeControl.BorderBrush = Avalonia.Media.Brush.Parse(BorderBrush.AsT2);
                        }
                    }
                    break;
                case nameof(BorderThickness):
                    if (!Equals(BorderThickness, value))
                    {
                        BorderThickness = (OneOf.OneOf<global::Avalonia.Thickness?, double, (double, double), (double, double, double, double), string>)value;
                        if (BorderThickness.IsT0)
                        {
                            NativeControl.BorderThickness = (global::Avalonia.Thickness)BorderThickness.AsT0;
                        }
                        else if (BorderThickness.IsT1)
                        {
                            NativeControl.BorderThickness = new global::Avalonia.Thickness(BorderThickness.AsT1);
                        }
                        else if (BorderThickness.IsT2)
                        {
                            NativeControl.BorderThickness = new global::Avalonia.Thickness(BorderThickness.AsT2.Item1,BorderThickness.AsT2.Item2);
                        }
                        else if (BorderThickness.IsT3)
                        {
                            NativeControl.BorderThickness = new global::Avalonia.Thickness(BorderThickness.AsT3.Item1,BorderThickness.AsT3.Item2,BorderThickness.AsT3.Item3,BorderThickness.AsT3.Item4);
                        }
                        else 
                        {
                            NativeControl.BorderThickness = global::Avalonia.Thickness.Parse(BorderThickness.AsT4);
                        }
                    }
                    break;
                case nameof(CornerRadius):
                    if (!Equals(CornerRadius, value))
                    {
                        CornerRadius = (OneOf.OneOf<global::Avalonia.CornerRadius?, double, (double, double), (double, double, double, double), string>)value;
                        if (CornerRadius.IsT0)
                        {
                            NativeControl.CornerRadius = (global::Avalonia.CornerRadius)CornerRadius.AsT0;
                        }
                        else if (CornerRadius.IsT1)
                        {
                            NativeControl.CornerRadius = new global::Avalonia.CornerRadius(CornerRadius.AsT1);
                        }
                        else if (CornerRadius.IsT2)
                        {
                            NativeControl.CornerRadius = new global::Avalonia.CornerRadius(CornerRadius.AsT2.Item1,CornerRadius.AsT2.Item2);
                        }
                        else if (CornerRadius.IsT3)
                        {
                            NativeControl.CornerRadius = new global::Avalonia.CornerRadius(CornerRadius.AsT3.Item1,CornerRadius.AsT3.Item2,CornerRadius.AsT3.Item3,CornerRadius.AsT3.Item4);
                        }
                        else 
                        {
                            NativeControl.CornerRadius = global::Avalonia.CornerRadius.Parse(CornerRadius.AsT4);
                        }
                    }
                    break;
                case nameof(FontFamily):
                    if (!Equals(FontFamily, value))
                    {
                        FontFamily = (OneOf.OneOf<global::Avalonia.Media.FontFamily,string>)value;
                        if (FontFamily.IsT0)
                        {
                            NativeControl.FontFamily = (global::Avalonia.Media.FontFamily)FontFamily.AsT0;
                        }
                        else 
                        {
                            NativeControl.FontFamily = global::Avalonia.Media.FontFamily.Parse(FontFamily.AsT1);
                        }
                    }
                    break;
                case nameof(FontFeatures):
                    if (!Equals(FontFeatures, value))
                    {
                        FontFeatures = (global::Avalonia.Media.FontFeatureCollection)value;
                        NativeControl.FontFeatures = FontFeatures;
                    }
                    break;
                case nameof(FontSize):
                    if (!Equals(FontSize, value))
                    {
                        FontSize = (double?)value;
                        NativeControl.FontSize = FontSize ?? (double)ACP.TemplatedControl.FontSizeProperty.GetDefaultValue(ACP.TemplatedControl.FontSizeProperty.OwnerType);
                    }
                    break;
                case nameof(FontStretch):
                    if (!Equals(FontStretch, value))
                    {
                        FontStretch = (global::Avalonia.Media.FontStretch?)value;
                        NativeControl.FontStretch = FontStretch ?? (global::Avalonia.Media.FontStretch)ACP.TemplatedControl.FontStretchProperty.GetDefaultValue(ACP.TemplatedControl.FontStretchProperty.OwnerType);
                    }
                    break;
                case nameof(FontStyle):
                    if (!Equals(FontStyle, value))
                    {
                        FontStyle = (global::Avalonia.Media.FontStyle?)value;
                        NativeControl.FontStyle = FontStyle ?? (global::Avalonia.Media.FontStyle)ACP.TemplatedControl.FontStyleProperty.GetDefaultValue(ACP.TemplatedControl.FontStyleProperty.OwnerType);
                    }
                    break;
                case nameof(FontWeight):
                    if (!Equals(FontWeight, value))
                    {
                        FontWeight = (global::Avalonia.Media.FontWeight?)value;
                        NativeControl.FontWeight = FontWeight ?? (global::Avalonia.Media.FontWeight)ACP.TemplatedControl.FontWeightProperty.GetDefaultValue(ACP.TemplatedControl.FontWeightProperty.OwnerType);
                    }
                    break;
                case nameof(Foreground):
                    if (!Equals(Foreground, value))
                    {
                        Foreground = (OneOf.OneOf<global::Avalonia.Media.IBrush, Avalonia.Media.Color, string>)value;
                        if (Foreground.IsT0)
                        {
                            NativeControl.Foreground = (global::Avalonia.Media.IBrush)Foreground.AsT0;
                        }
                        else if (Foreground.IsT1)
                        {
                            NativeControl.Foreground = new global::Avalonia.Media.Immutable.ImmutableSolidColorBrush(Foreground.AsT1);
                        }
                        else 
                        {
                            NativeControl.Foreground = Avalonia.Media.Brush.Parse(Foreground.AsT2);
                        }
                    }
                    break;
                case nameof(Padding):
                    if (!Equals(Padding, value))
                    {
                        Padding = (OneOf.OneOf<global::Avalonia.Thickness?, double, (double, double), (double, double, double, double), string>)value;
                        if (Padding.IsT0)
                        {
                            NativeControl.Padding = (global::Avalonia.Thickness)Padding.AsT0;
                        }
                        else if (Padding.IsT1)
                        {
                            NativeControl.Padding = new global::Avalonia.Thickness(Padding.AsT1);
                        }
                        else if (Padding.IsT2)
                        {
                            NativeControl.Padding = new global::Avalonia.Thickness(Padding.AsT2.Item1,Padding.AsT2.Item2);
                        }
                        else if (Padding.IsT3)
                        {
                            NativeControl.Padding = new global::Avalonia.Thickness(Padding.AsT3.Item1,Padding.AsT3.Item2,Padding.AsT3.Item3,Padding.AsT3.Item4);
                        }
                        else 
                        {
                            NativeControl.Padding = global::Avalonia.Thickness.Parse(Padding.AsT4);
                        }
                    }
                    break;
                case nameof(Template):
                    Template = (RenderFragment)value;
                    break;
                case nameof(OnTemplateApplied):
                    if (!Equals(OnTemplateApplied, value))
                    {
                        void NativeControlTemplateApplied(object sender, ACP.TemplateAppliedEventArgs e) => InvokeEventCallback(OnTemplateApplied, e);

                        OnTemplateApplied = (EventCallback<ACP.TemplateAppliedEventArgs>)value;
                        NativeControl.TemplateApplied -= NativeControlTemplateApplied;
                        NativeControl.TemplateApplied += NativeControlTemplateApplied;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddControlTemplateProperty<ACP.TemplatedControl, Avalonia.Controls.Templates.IControlTemplate>(builder, sequence++, Template,
                (nativeControl, nativeTemplate) => nativeControl.Template = nativeTemplate);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
