// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using ACS = Avalonia.Controls.Shapes;
using BlazorBindingsAvalonia.Elements;

#pragma warning disable CA2252

namespace BlazorBindingsAvalonia.Elements.Shapes
{
    public partial class Line : Shape
    {
        static Line()
        {
            RegisterAdditionalHandlers();
        }

        [Parameter] public OneOf.OneOf<global::Avalonia.Point?, string> EndPoint { get; set; }
        [Parameter] public OneOf.OneOf<global::Avalonia.Point?, string> StartPoint { get; set; }

        public new ACS.Line NativeControl => (ACS.Line)((AvaloniaObject)this).NativeControl;

        protected override ACS.Line CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(EndPoint):
                    if (!Equals(EndPoint, value))
                    {
                        EndPoint = (OneOf.OneOf<global::Avalonia.Point?,string>)value;
                        if (EndPoint.IsT0)
                        {
                            NativeControl.EndPoint = (global::Avalonia.Point)EndPoint.AsT0;
                        }
                        else 
                        {
                            NativeControl.EndPoint = global::Avalonia.Point.Parse(EndPoint.AsT1);
                        }
                    }
                    break;
                case nameof(StartPoint):
                    if (!Equals(StartPoint, value))
                    {
                        StartPoint = (OneOf.OneOf<global::Avalonia.Point?,string>)value;
                        if (StartPoint.IsT0)
                        {
                            NativeControl.StartPoint = (global::Avalonia.Point)StartPoint.AsT0;
                        }
                        else 
                        {
                            NativeControl.StartPoint = global::Avalonia.Point.Parse(StartPoint.AsT1);
                        }
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
